// Generated by Vexel compiler
// https://github.com/vexel-lang/vexel
// Dead code elimination: only reachable functions and referenced globals/types are generated

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

#ifndef VX_MUTABLE
#define VX_MUTABLE
#endif
#ifndef VX_NON_MUTABLE
#define VX_NON_MUTABLE const
#endif
#ifndef VX_CONSTEXPR
#define VX_CONSTEXPR const
#endif

// VEXEL: kind=extern export=no reentrant=yes ref_mask=- pure=no no_global_write=no abi=native
float vx_seedf(
);
// VEXEL: kind=extern export=no reentrant=yes ref_mask=- pure=no no_global_write=no abi=native
uint32_t vx_f32_as_u32(
float vx_x
);



#ifndef VX_FARPTR
#define VX_FARPTR(mod, addr) ((((uint32_t)(mod)) << 16) | ((uint16_t)(addr)))
#endif
#ifndef VX_FARPTR_MOD
#define VX_FARPTR_MOD(ptr) ((uint8_t)(((uint32_t)(ptr) >> 16) & 0xFF))
#endif
#ifndef VX_FARPTR_ADDR
#define VX_FARPTR_ADDR(ptr) ((uint16_t)((uint32_t)(ptr) & 0xFFFF))
#endif
void vx_load_module_id_a(uint8_t seg);
void vx_load_module_id_b(uint8_t seg);
uint16_t vx_strlen_far_a(uint32_t ptr);
uint16_t vx_strlen_far_b(uint32_t ptr);
extern const uint8_t __ML_SEGMENT_A_vx_main__reent__from_entry__pA;
extern const uint8_t __ML_SEGMENT_B_vx_main__reent__from_entry__pA;
int32_t vx_main__reent__from_entry__pA(void);
__nonbanked int32_t main(void);
